block/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from muhammadamin import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('muhammadamin.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

muhammadamin/urls.py
from django.urls import path

from .views import AboutView, Post_Create_View, Post_Delete_View, Post_Detail_View, Register_view, Logout_view, \
    Login_view, home_page, profile_page

app_name = 'muhammadamin'
urlpatterns = [
    path('', home_page, name='home_page'),
    path('home.html/', home_page, name='home_page'),
    path('about.html/', AboutView.as_view(), name='about_page'),
    path('profile.html/', profile_page, name='profile_page'),
    path('post_form.html/', Post_Create_View.as_view(), name='post_create_page'),
    path('register.html/', Register_view, name='register_page'),
    path('login.html/', Login_view, name='login_page'),
    path('logout/', Logout_view, name='logout_page'),
    path('post_detail.html/', Post_Detail_View, name='post_detail_page'),
    path('post_conifirm_delete.html/', Post_Delete_View, name='post_delete_page'),
]

muhammadamin/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class AbstractBsedModel(models.Model):
    created_ad = models.DateTimeField(auto_now_add=True)
    updated_ad = models.DateTimeField(auto_now=True)


class Post(AbstractBsedModel):
    title = models.CharField(max_length=30)
    content = models.TextField()

    def __str__(self):
        return self.title


class About(AbstractBsedModel):
    title = models.CharField(max_length=38)
    description = models.TextField()

    def __str__(self):
        return self.title


class Author(AbstractBsedModel):
    Choice_gender = [
        ('m', "Male"),
        ('f', "Female"),
    ]
    user_name = models.CharField(max_length=30)
    gender = models.CharField(max_length=6, choices=Choice_gender, null=True)
    age = models.IntegerField(null=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()
    posts = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='posts')

muhammadamin/forms.py
from django import forms
# from django.db.transaction import commit

from .models import Post, Author
from django.core.exceptions import ValidationError


class Create_Post_Form(forms.Form):
    title = forms.CharField(max_length=30)
    content = forms.CharField(widget=forms.Textarea)
    class Meta:
        models = Post
        fields = ['title', 'content']

    def save(self):
        title = self.cleaned_data['title']
        content = self.cleaned_data['content']
        Post.objects.create(title=title, content=content)


class Register_Form(forms.Form):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    username = forms.CharField(max_length=30)
    age = forms.IntegerField()
    gender = forms.ChoiceField(choices=[('M', 'Male'), ('F', 'Female')])
    email = forms.EmailField()
    password1 = forms.CharField(max_length=50)
    password2 = forms.CharField(max_length=50)

    def save(self, commit=True):
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]

        if password1 == password2:
            user = super().save(commit)
            user.set_password(password1)
            user.save()
        else:
            raise ValidationError("Password must be match")

    class Meta:
        models = Author
        fields = ['username', 'gender', 'age', 'first_name', 'last_name', 'email', 'posts']


class Login_Form(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(max_length=50)

muhammadamin/views.py
from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.shortcuts import render, redirect
from django.views import View
from .forms import Create_Post_Form, Login_Form, Register_Form

from .models import About, Post


def profile_page(request):
    posts = Post.objects.all()
    return render(request, 'muhammadamin/profile.html', {"posts": posts})


# def about_page(request):
#     abouts = About.objects.all()
#     return render(request, 'muhammadamin/about.html', abouts)


class AboutView(View):
    def get(self, request):
        abouts = About.objects.all()
        return render(request, 'muhammadamin/about.html', {'abouts': abouts})


class Post_Create_View(View):
    model = Post
    form = Create_Post_Form
    fields = ["name", "books"]
    success_message = 'Post successfully created'
    template_name = "muhammadamin/post_form.html"

    def post(self, request):
        form = Create_Post_Form(request.POST)
        if form.is_valid():
            post = form.save()
            return redirect('muhammadamin:home_page')
        else:
            return render(request, self.template_name, {'form': form})

    def get(self, request):
        form = Create_Post_Form()
        return render(request, self.template_name, {'form': form})


def Post_Detail_View(request):
    posts = Post.objects.all()
    return render(request, 'muhammadamin/post_detail.html', {"posts": posts})


def Post_Delete_View(request):
    if request.method == 'POST':
        request.POST.delete()
    return render(request, "muhammadamin/post_confirm_delete.html ")


def Register_view(request):
    if request.method == 'POST':
        form = Register_Form(data=request.POST)
        if form.is_valid():
            messages.success(request, "User successfully registered")
            return render(request, "muhammadamin/home.html")
        else:

            return render(request, "muhammadamin/register.html", context={"form": form})
    elif request.method == 'GET':
        form = Register_Form(request.GET)
        return render(request, "muhammadamin/register.html", context={"form": form})


def Login_view(request):
    if request.method == 'POST':
        form = Login_Form(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                print(request.COOKIES)
                messages.success(request, "user successfully logged in")
                return redirect("muhammadamin:home_page")
            else:
                messages.error(request, "Username or password wrong")
                return redirect("muhammadamin:login_page")
        else:
            messages.error(request, "User didn't login correctly")
            return render(request, "muhammadamin/login.html", context={"form": form})

    else:
        form = Login_Form(data=request.GET)
        return render(request, "muhammadamin/login.html", context={"form": form})


def Logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('muhammadamin:home_page ')
    else:
        logout(request)
        return render(request, "muhammadamin/home.html")


def home_page(request):
    return render(request, "muhammadamin/home.html")

templates/muhammadamin/about.html
{% extends "muhammadamin/base.html" %}
{% block title %} About Page {% endblock %}
{% block body %}
    <h1>About Page</h1>
    {% for about in abouts %}
        <h5>{{ about.title }}</h5>
        {{ about.description }}
    
    {% endfor %}
{% endblock %}

templates/muhammadamin/base.html
<html>
<head>
    {% if user.is_authenticated %}
        <a href={% url 'muhammadamin:logout_page' %}#">Log out Author</a><br><br>
    {% else %}
        <a href="{% url 'muhammadamin:login_page' %}"> Login Author</a><br><br>
        <a href="{% url 'muhammadamin:register_page' %}"> Register Author</a><br><br>
    {% endif %}
    <a href={% url "muhammadamin:home_page" %}>Home</a>
    <a href={% url "muhammadamin:about_page" %}>About</a>
    <a href={% url "muhammadamin:post_create_page" %}>New Post </a>
    <a href={% url "muhammadamin:profile_page" %}>Profile </a>
    {#    <a href={% url "muhammadamin:logout_page" %}>Logout </a>#}
    {#    <a href={% url "muhammadamin:login_page" %}>Login </a>#}
    {#    <a href={% url "muhammadamin:register_page" %}>Register </a>#}
</head>
<head>
    <title>
        {% block title %}
            Base html
        {% endblock %}
    </title>
</head>
<body>
{% if messages %}
    <ul>
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>

{% endif %}

{% block body %}

{% endblock %}

</body>


</html>

templates/muhammadamin/home.html
{% extends "muhammadamin/base.html" %}
{% load static %}
{% block tile %} Home Page {% endblock %}
{% block body %}
    <br>
    <br>
    <br>
    <br>
    <h1>Home Page</h1>
    <br>
    <br>
    <br>
    <img class="rounded-circle article-img" src={% static "images/muhammadamin/gibbs.jpeg" %}>x
    <h1><a href="post_detail.html" > Jordan Gibbs</a><br><br></h1>
    <img class="rounded-circle article-img" src={% static "images/muhammadamin/andrew.jpeg" %}>x
    <h1><a href="post_detail.html" > Andrew </a><br><br></h1>
{% endblock %}

templates/muhammadamin/login.html
<h2>Log In</h2>
<form method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Log In</button>
</form>

templates/muhammadamin/post_confirm_delete.html
{% extends "muhammadamin/base.html" %}
{% block title %} Delete Page {% endblock %}
{% block body %}
    <body>
    <br>
    <br>
    <br>
    <a href="{% url 'muhammadamin:post_delete_page' %}" methods="POST">Yes, Delete </a> 
    <br>
    <br>
    <a href="{% url 'muhammadamin:profile_page' %}">Cancel</a>
</body>
{% endblock %}

templates/muhammadamin/post_detail.html
{% extends "muhammadamin/base.html" %}
{% block title %} Post Detail {% endblock %}
{% block body %}

    <h1>Title : {{ post.title }}</h1><br>
    Content : {{ post.content }}<br>
<br><br><br><br>
{% endblock %}

templates/muhammadamin/post_form.html
<a href={% url "muhammadamin:home_page" %}>Home</a>

<a href={% url "muhammadamin:about_page" %}>About</a>
<a href={% url "muhammadamin:post_create_page" %}>New Post </a>
<a href={% url "muhammadamin:profile_page" %}>Profile </a>
<a href={% url "muhammadamin:logout_page" %}>Logout </a>
<a href={% url "muhammadamin:login_page" %}>Login </a>
<a href={% url "muhammadamin:register_page" %}>Register </a>
<form method="post">
    {% block title %} Create Post {% endblock %}
    {% block body %}

        <form method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit">Create</button>
        </form>
    {% endblock %}

templates/muhammadamin/register.html
<h2>Register</h2>
<form method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Register</button>
</form>

templates/muhammadamin/user_posts.html
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="main.css">
        <title>Django Blog</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="#">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="#">Home</a>
              <a class="nav-item nav-link" href="about.html">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="post_form.html">New Post</a>
                <a class="nav-item nav-link" href="user_posts.html">Profile</a>
                <a class="nav-item nav-link" href="#">Logout</a>
                <a class="nav-item nav-link" href="login.html">Login</a>
                <a class="nav-item nav-link" href="register.html">Register</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
              <div class="alert alert-{{ message.tags }}">
                <h6>Django messages might be shown here</h3>
              </div>
            <h1 class="mb-3">Posts by Andrew Ng </h1>
         
            <article class="media content-section">
              <img class="rounded-circle article-img" src="../../media/muhammadamin/andrew.jpeg">
              <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="user_posts.html">Andrew Ng</a>
                  <small class="text-muted">Aug 21, 2019</small>
                </div>
                <h4><a class="article-title" href="post_detail.html">AI in Latin America: Announcing our first international office in Colombia</a></h2>
                <p class="article-content">I am excited to announce the opening of our office in Medellín, Colombia. 
                  The office will serve as the Latin American headquarters for three of the companies in our AI ecosystem</p>
              </div>
            </article>
            <article class="media content-section">
              <img class="rounded-circle article-img" src="../../media/muhammadamin/andrew.jpeg">
              <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="user_posts.html">Andrew Ng</a>
                  <small class="text-muted">Aug 21, 2019</small>
                </div>
                <h4><a class="article-title" href="post_detail.html">Introducing the AI Transformation Playbook</a></h2>
                <p class="article-content">Dear friends,
                  I’m excited to share with you the AI Transformation Playbook. Drawn from my experience leading Google Brain, 
                  Baidu’s AI Group, and Landing AI, this Playbook provides a roadmap for your company to transform into a great AI company.</p>
              </div>
            </article>
            
        
          </div>
      <div class="col-md-4">
        <div class="content-section">
          <h3>Our Sidebar</h3>
          <p class='text-muted'>You can put any information here you'd like.
            <ul class="list-group">
              <li class="list-group-item list-group-item-light">Latest Posts</li>
              <li class="list-group-item list-group-item-light">Announcements</li>
              <li class="list-group-item list-group-item-light">Calendars</li>
              <li class="list-group-item list-group-item-light">etc</li>
            </ul>
          </p>
        </div>
      </div>
      </div>
      </main>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>
              